### testing api call

### user
###getUser

GET http://localhost:8000/api/v1/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYSIsImlhdCI6MTc3ODg2NTExMywiZXhwIjoxNzc5NDY5OTEzfQ.3C8lG-FKB282IjRNtph9gJgCh63bfcELda4CleACV68
###post new user
### login user
POST  http://localhost:8000/api/v1/users/login
Content-Type: application/json
 
 {
   
    "email":"a@a",
    "password":"1111"

 }


###transaction all private router



### post new transaction 

POST  http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYSIsImlhdCI6MTc3ODg2NTExMywiZXhwIjoxNzc5NDY5OTEzfQ.3C8lG-FKB282IjRNtph9gJgCh63bfcELda4CleACV68

{
   "type":"income",
   "title":"salary",
   "amount":"5000", 
   "tdate": "01-01-2024"

}

### get all transactions 

GET  http://localhost:8000/api/v1/transactions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYSIsImlhdCI6MTc3ODE3NjUyMSwiZXhwIjoxNzc4NzgxMzIxfQ.KGgOOc6ybIXVRObRyrZ2nAaIsqlRoyeSPRDpzM_U6pM


### delete transaction for specific user 
DELETE http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYSIsImlhdCI6MTc4MDMyOTI3NiwiZXhwIjoxNzgwOTM0MDc2fQ.HeDiCY5JPmn46EH1VzaJiM8TYUOdaeslKH1zqziD_rY


[
   "69f4d8229f1b2a8e74c51113" , "69a31c2e7c3fb9c931b37aa4"
]