### testing api call

### user
###getUser

GET http://localhost:8000
###post new user
POST  http://localhost:8000/api/v1/users
Content-Type: application/json
 
 {
    "name":"shikamaru",
    "email":"shikamaru@gmail.com",
    "password": "23"

 }


###transaction
